site_name: ChuckDeviceController
site_url: https://github.com/versx/ChuckDeviceController
site_description: ChuckDeviceController
site_author: versx

repo_url: https://github.com/versx/chuckdevicecontroller/
edit_uri: ""

theme:
    name: readthedocs #mkdocs, bootstrap4, cinder, cosmo, cyborg, flatly, ivory, material, readthedocs, slate, yeti

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: en

nav:
    - General:
        - Home: index.md
        - Screenshots: screenshots.md
        - Features: features.md
        - Requirements: requirements.md
        - Getting Started: getting-started.md
    - Applications:
        - ChuckDeviceConfigurator: applications/configurator.md
        - ChuckDeviceController: applications/controller.md
        - ChuckDeviceCommunicator: applications/communicator.md
        - ChuckDeviceProxy: applications/proxy.md
    - Configuration:
        - Configuration: configs/index.md
        - ChuckDeviceConfigurator: configs/configurator.md
        - ChuckDeviceController: configs/controller.md
        - ChuckDeviceCommunicator: configs/communicator.md
        - ChuckDeviceProxy: configs/proxy.md
    - Plugin System:
        - Plugins: plugin-system/index.md
        - Visual Studio Templates: plugin-system/project-templates.md
        - API Documentation: plugin-system/api.md
        - Plugin Host Interfaces: plugin-system/interfaces.md
        - Plugin Entity Interfaces: plugin-system/entity-interfaces.md
        - Plugins Included: plugin-system/plugins-included.md
        - Examples: plugin-system/examples.md
    - Plugins Included:
        - BitbucketAuthProviderPlugin: plugins/BitbucketAuthProviderPlugin.md
        - DeviceAuthPlugin: plugins/DeviceAuthPlugin.md
        - Example.DotNetCorePlugin: plugins/Example.DotNetCorePlugin.md
        - FindyJumpyPlugin: plugins/FindyJumpyPlugin.md
        - GitLabAuthProviderPlugin: plugins/GitLabAuthProviderPlugin.md
        - HealthChecksPlugin: plugins/HealthChecksPlugin.md
        - MemoryBenchmarkPlugin: plugins/MemoryBenchmarkPlugin.md
        - MicrosoftAuthProviderPlugin: plugins/MicrosoftAuthProviderPlugin.md
        - MiniProviderPlugin: plugins/MiniProviderPlugin.md
        - PogoEventsPlugin: plugins/PogoEventsPlugin.md
        - RazorTestPlugin: plugins/RazorTestPlugin.md
        - RedditAuthProviderPlugin: plugins/RedditAuthProviderPlugin.md
        - RequestBenchmarkPlugin: plugins/RequestBenchmarkPlugin.md
        - RobotsPlugin: plugins/RobotsPlugin.md
        - TestPlugin: plugins/TestPlugin.md
        - TodoPlugin: plugins/TodoPlugin.md
        - VisualStudioAuthProviderPlugin: plugins/VisualStudioAuthProviderPlugin.md
    - Miscellaneous:
        - 3rd Party Authentication: other/3rd-party-auth.md
        - Custom Settings: other/custom-settings.md
    - About:
        - Dedication: dedication.md


markdown_extensions:
    - toc:
        permalink: 

copyright: Copyright &copy; 2022, Maintained by <a href="https://github.com/versx">versx</a>.

extra_css:
    - css/base.css
    - css/bootstrap-custom.min.css
