site_name: ChuckDeviceController
site_url: https://github.com/versx/ChuckDeviceController
site_description: ChuckDeviceController
site_author: versx

docs_dir: docs/

repo_url: https://github.com/versx/chuckdevicecontroller/
repo_name: GitHub

theme:
    name: readthedocs #mkdocs, bootstrap4, cinder, cosmo, cyborg, flatly, ivory, material, readthedocs, slate, yeti
    #custom_dir: 'themes/material/'
    nav_style: dark
    locale: en
    favicon: img/favicon.ico
    logo: img/chuck.gif
    analytics:
        gtag: UA-75960523-2
    font:
        text: Roboto
    highlightjs: True
    hljs_languages:
        - csharp
        - json
    sticky_navigation: False

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: en

nav:
    - General:
        - Home: index.md
        - Screenshots: screenshots.md
        - Install Requirements: requirements.md
        - Getting Started: getting-started.md
    - Applications:
        - ChuckDeviceConfigurator: applications/configurator.md
        - ChuckDeviceController: applications/controller.md
        - ChuckDeviceCommunicator: applications/communicator.md
        - ChuckDeviceProxy: applications/proxy.md
    - Plugin System:
        - Create a Plugin: plugin-system/create-a-plugin.md
        - API Documentation: plugin-system/api.md
        - Examples: plugin-system/examples.md
        - Host Interfaces: plugin-system/host-interfaces.md
        - Entity Interfaces: plugin-system/entity-interfaces.md
        - Visual Studio Templates: plugin-system/project-templates.md
    - Plugins Included:
        - Overview: plugins/overview.md
        - BitbucketAuthProviderPlugin: plugins/BitbucketAuthProviderPlugin.md
        - DeviceAuthPlugin: plugins/DeviceAuthPlugin.md
        - Example.DotNetCorePlugin: plugins/Example.DotNetCorePlugin.md
        - FindyJumpyPlugin: plugins/FindyJumpyPlugin.md
        - GitLabAuthProviderPlugin: plugins/GitLabAuthProviderPlugin.md
        - HealthChecksPlugin: plugins/HealthChecksPlugin.md
        - MemoryBenchmarkPlugin: plugins/MemoryBenchmarkPlugin.md
        - MicrosoftAuthProviderPlugin: plugins/MicrosoftAuthProviderPlugin.md
        - MiniProviderPlugin: plugins/MiniProviderPlugin.md
        - PogoEventsPlugin: plugins/PogoEventsPlugin.md
        - RazorTestPlugin: plugins/RazorTestPlugin.md
        - RedditAuthProviderPlugin: plugins/RedditAuthProviderPlugin.md
        - RequestBenchmarkPlugin: plugins/RequestBenchmarkPlugin.md
        - RobotsPlugin: plugins/RobotsPlugin.md
        - TestPlugin: plugins/TestPlugin.md
        - TodoPlugin: plugins/TodoPlugin.md
        - VisualStudioAuthProviderPlugin: plugins/VisualStudioAuthProviderPlugin.md
    - Miscellaneous:
        - 3rd Party Authentication: other/3rd-party-auth.md
        - Custom Settings: other/custom-settings.md
    - About:
        - Dedication: about/dedication.md
        - Credits: about/credits.md
        - TODO: about/todo.md
        - GitHub: https://github.com/versx/ChuckDeviceController
        - Author: https://github.com/versx


markdown_extensions:
    - toc:
        permalink: 

copyright: Copyright &copy; 2022, Maintained by <a href="https://github.com/versx">versx</a>.

extra_css:
    - css/base.css
    - css/bootstrap-custom.min.css
    - css/custom.css
