version: '3.4'

services:
  chuckdeviceconfigurator:
    image: ${DOCKER_REGISTRY-}chuckdeviceconfigurator
    build:
      context: .
      dockerfile: ../ChuckDeviceConfigurator/Dockerfile
  chuckdevicecontroller:
    image: ${DOCKER_REGISTRY-}chuckdevicecontroller
    build:
      context: .
      dockerfile: ../ChuckDeviceController/Dockerfile
  chuckdevicecommunicator:
    image: ${DOCKER_REGISTRY-}chuckdevicecommunicator
    build:
      context: .
      dockerfile: ../ChuckDeviceCommunicator/Dockerfile
  chuckdeviceproxy:
    image: ${DOCKER_REGISTRY-}chuckdeviceproxy
    build:
      context: .
      dockerfile: ../ChuckDeviceProxy/Dockerfile